version: '3'
services:
    jenkins:
      image: jenkins/jenkins
      ports:
      - "8880:8080"
      - "50000:50000"
      volumes:
      - /var/lib/docker/volumes/jenkins_volume:/var/jenkins_home
      networks:
        - docker_network
    ubuntu:
      build: /home/panda/projects/slave
      networks:
        - docker_network
      depends_on:
      - "jenkins"
networks:
  docker_network:
    driver: bridge
