version: '3'

services:
  jenkins:
    image: jenkins/jenkins:jdk11
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      - ../volumes/jenkins/:/var/jenkis_home/
    networks:
      - docker_network
  ubuntu_slave:
    depends_on:
      - jenkins
    container_name: ubuntu
    volumes:
      - /var/run/docker.sock/:/var/run/docker.sock/
    build:
      context: ../dockserfiles/slave/
    command:
      - java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/jenkins-agent.jnlp -secret 5093c9cb7cea69fc33431198b10524f85141cf283c052600b84f985e124048d5 -workDir "/home/"
    networks:
      - docker_network
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ../volumes/artifactory/:/var/opt/jfrog/artifactory
    networks:
      - docker_network
  selenium_hub:
  selenium_firefox:
networks:
  docker_network:
    driver: bridge