---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01f0ee504gqpmkzzn2x7hpf3sx"
    - from: "jfmd@*"
      to: "jfmd@01f0ee52frj430p7mhnyymj0qt"
    - from: "jfrt@*"
      to: "jfrt@01f0ee59rzdypp0wd25tvx1wd1"
    - from: "jffe@*"
      to: "jffe@000"
schema-version: 2
