---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01ez5bs3r314xmq2cc5j3k7vn8"
    - from: "jfevt@*"
      to: "jfevt@01ez5brynwf90j101b6e1x19gb"
    - from: "jfmd@*"
      to: "jfmd@01ez5bs5y2qpwy0sj9ah4cpd6z"
    - from: "jfrt@*"
      to: "jfrt@01ez5bsggjc7h01x9d4aqs0mc0"
    - from: "jffe@*"
      to: "jffe@000"
licenses:
- server-name: "041b93e8ce49"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlORlF4Tnpvek1EbzFNaTR5T0RaYUNtbGtPaUExTVRBME1HTmhOeTFqT1RaaUxUUmpOVFF0\r\
    \nWVRVME9TMW1OekE1WXpsaFlqVTBPVFlLYjNkdVpYSTZJR0Z6WkdFS2NISnZjR1Z5ZEdsbGN6b2dl\r\
    \nMzBLYzJsbmJtRjBkWEpsT2lCdWRXeHNDblJ5YVdGc09pQjBjblZsQ25SNWNHVTZJRlJTU1VGTUNu\r\
    \nWmhiR2xrUm5KdmJUb2dNakF5TVMwd01pMHlNbFF4Tnpvek1EbzFNaTR5T0RaYUNnPT0KICAgIHNp\r\
    \nZ25hdHVyZTogRDZnR0RoMUF4MXloVWU1c2lSdUgyUGZPWTVzRXc1Vmt3U0M1MTY3THVMaDJkbmtS\r\
    \nOEwzZEZSU0xmOGh1NFc5MmJNY0VnaVMvcTljVnNiTW5TM1lnUEMrbG5qRC8xV3pTL2UzL1dhVndj\r\
    \neHd0bHM2Lzk4RmZOT1krNUs4Y0NTM2MrYkVjTkhDaGttN2hodkwxUnAvTDM2YStpYUp6UTBrQkNF\r\
    \naTJRekR1NUJUM20xcjgyRFUxdEJQZTcvQ0N5L1dDcExLcUxGTzZrY0gxSmFJR2daVXVkakFna0pm\r\
    \nMHBFYVN5dHNYc09JN3pUMjUrQlZacHZYTHE5ZWd5dDRNMjA2amM1Slh2T3RnYzQ5aUhEUUFBN1RZ\r\
    \ncUpkNFp4cTBNTlo5RWRXQjd3c0oydkt0aXFFY1JYZW1tNHM4Wk5uYnovaEV2aVlxNW8vVEFIUFox\r\
    \nalowR0JzUWJBPT0KdmVyc2lvbjogMQo=\r\n"
schema-version: 2
